

""" custom exception which inherits from ValueError"""
class UrlMalformedException(ValueError):

    pass


